# -*- coding: utf-8 -*-
"""factorial.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Xl9Cd20e1N-Act-Q-rQLK1AftcuIQvX3
"""

fact = 1

for i in range(1, 6):
    fact = fact * i

print("Factorial of 5 =", fact)